"""add is_approved

Revision ID: 48774b4fb75e
Revises: 6d2185e877f6
Create Date: 2026-04-10 03:37:27.033265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48774b4fb75e'
down_revision: Union[str, Sequence[str], None] = '6d2185e877f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_approved', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_approved')
    # ### end Alembic commands ###
